---
- name: Install docker
  command: "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
  notify: start_service
- meta: flush_handlers

# - name: copy app files
#   copy:
#     # src: ../../../../../../../programming/
#     src: files/app/
#     dest: /home/vagrant/app/

# - name: build app image
#   # command: docker image build /home/vagrant/app/ -t api-app
#   docker_image:
#     name: app-api
#     build:
#       path: /home/vagrant/app/

- name: Create container
  docker_container:
    name: halan-api-app
    image: amogahed2019/halan-api
    restart: yes
    ports:
    - "80:5050"
    env:
      MASTERDB_PRIVATE_IP: "{{ MASTERDB_PRIVATE_IP }}" 
      DB_NAME: "{{ DB_NAME }}" 
      DB_USER_NAME: "{{ DB_USER_NAME }}" 
      DB_USER_PASS: "{{ DB_USER_PASS }}" 