---

- name: Instll yum packages
  yum:
    name: yum-utils
    state: latest
    disable_gpg_check: yes

- name: Add Docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: latest
    disable_gpg_check: yes
  notify: start_service

- meta: flush_handlers

- name: Create container
  docker_container:
    name: halan-api-app
    image: amogahed2019/halan-api
    restart: yes
    ports:
    - "80:5050"
    env:
      MASTERDB_PRIVATE_IP: "{{ MASTERDB_PRIVATE_IP }}" 
      DB_NAME: "{{ DB_NAME }}" 
      DB_USER_NAME: "{{ DB_USER_NAME }}" 
      DB_USER_PASS: "{{ DB_USER_PASS }}" 

- name: Start and Enable firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Add Port 80 to firewall
  firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
  notify: firewall_reload