---
- name: Stop postgres Service
  systemd:
    name: postgresql-13
    state: stopped

- name: Moving old conf.
  command: sudo -u postgres -s mv /var/lib/pgsql/13/data/ /var/lib/pgsql/13/data-bacup/

- name: copy conf files and link replica
  expect:
    command: sudo -u postgres -s pg_basebackup -h 192.168.44.11 -D /var/lib/pgsql/13/data -U replica -v -P -R -X stream -C -S pgstandby1
    responses:
      (?i)password: "replica"
  notify: restart_service

