version: '3.5'

services:
  api:
    restart: always
    build: .
    ports: 
      - '80:5000'
    depends_on:
      - psql

  psql:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: mypasswd
      POSTGRES_USER: devops
      POSTGRES_DB: devops
    ports:
      - '5432:5432'
    volumes: 
      - psql-data:/var/lib/postgresql/data


volumes:
  psql-data: