version: '3.5'

services:
  psql:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: mypasswd
      POSTGRES_USER: devops
      POSTGRES_DB: devops
    ports:
      - '5432:5432'
    volumes: 
      - psql-data:/var/lib/postgresql/data
  
  api:
    image: amogahed2019/halan-api
    restart: always
    environment:
      MASTERDB_PRIVATE_IP: psql
      DB_USER_NAME: devops
      DB_NAME: devops
      DB_USER_PASS: devops
    ports: 
      - '80:5050'
    depends_on:
      - psql


volumes:
  psql-data: