---
- name: Make Server listens on any address
  command: sudo -u postgres -s psql -c "ALTER SYSTEM SET listen_addresses TO '*';"

- name: Create databaseuser for connection
  expect:
    command: sudo -u postgres -s createuser --superuser -P -e devops # db_user and pass as vars
    responses:
      (?i)password: "devops"
      (?i)again: "devops"

- name: Create replica User for database replication
  expect:
    command: sudo -u postgres -s createuser --replication -P -e replica # db_replpass as var
    responses:
      (?i)password: "replica"
      (?i)again: "replica"
    
  # shell: sudo -u postgres -s createuser --replication -P -e replica
  # stdin:
  #   - replica
  #   - replica


- name: edit pg_hda.conf file
  lineinfile:
    path: /var/lib/pgsql/13/data/pg_hba.conf
    line: host	replication 	replica 	10.0.0.12/8		md5 # dbs_ip as variables
    state: present
  notify: restart_service

- meta: flush_handlers

- name: Create DataBase
  command: sudo -u postgres -s psql -c "create database devops;" # database name as variable
  
  
  