# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Box settings
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

# multi vm provisioning
N = 3
(1..N).each do |machine_id|
  config.vm.define "machine#{machine_id}" do |machine|
    machine.vm.hostname = "machine#{machine_id}"
    machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "node#{machine_id}"  
    end
    # Only execute once the Ansible provisioner,
    # when all the machines are up and ready.
    machine.vm.provision "shell", inline: <<-SHELL
      yum update   
      yum install -y git
    SHELL
    if machine_id == N
        # machine.vm.provision :ansible do |ansible|
        #   # Disable default limit to connect to all the machines
        #   ansible.limit = "all"
        #   ansible.playbook = "playbook.yml"
      # end
    end
  end
end


  # # Provider settings
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = 2048
  #   vb.cpus = 2
  #   vb.name = "node1"  
  # end

  # # Provisioning settings
  # config.vm.provision "shell", inline: <<-SHELL
  #   yum update   
  #   yum install -y git
  # SHELL

end
