# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    # Box settings
    config.vm.box = "centos/8"
    config.vm.box_check_update = false
  
  # multi vm provisioning
  N = 3
  (1..N).each do |machine_id|
    config.vm.define "node#{machine_id}" do |machine|
      machine.vm.hostname = "node#{machine_id}.halanapp.org"
      machine.vm.network "private_network", ip: "192.168.44.#{9+machine_id}"
      machine.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.name = "node#{machine_id}"
      end

      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.playbook = "../ansible/mproj.yaml"
          ansible.limit= "all"
          ansible.become = true
          # ansible.extra_vars = { 
          #   ansible_python_interpreter: "/usr/bin/python3"
          # }
          # ansible.inventory_path= "../ansible/hosts"
          ansible.groups = {
            "APP" => ["node1"],
            "DBM" => ["node2"],
            "DBS" => ["node3"],
            "DBC" => ["node[2:3]"]
          }
        end
      end
    end
  end
end
  