---
- name: Make Server listens on any address
  command: sudo -u postgres -s psql -c "ALTER SYSTEM SET listen_addresses TO '*';"

- name: Create databaseuser for connection
  become_user: postgres
  postgresql_user:
    name: "{{ DB_USER_NAME }}"
    password: "{{ DB_USER_PASS }}"
    role_attr_flags: "SUPERUSER"
    state: present

- name: Create replica User for database replication
  become_user: postgres
  postgresql_user:
    name: "{{ DB_REPLICA_NAME }}"
    password: "{{ DB_REPLICA_PASS }}"
    role_attr_flags: "REPLICATION"
    state: present


- name: Add replica user entry in pg_hda.conf file
  postgresql_pg_hba:
    dest: /var/lib/pgsql/13/data/pg_hba.conf
    contype: host
    users: "{{ DB_REPLICA_NAME }}" 
    source: "{{ SLAVEDB_PRIVATE_IP }}/24"
    databases: replication


- name: Add db_user entry in pg_hda.conf file
  postgresql_pg_hba:
    dest: /var/lib/pgsql/13/data/pg_hba.conf
    contype: host
    users: "{{ DB_USER_NAME }}" 
    source: "{{ APP_PRIVATE_IP }}/24"
    databases: all
  notify: restart_service

- meta: flush_handlers

- name: Create DataBase
  command: sudo -u postgres -s psql -c "create database {{ DB_NAME }};" #  DB_NAME
  
  
  